# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DebugFlatbuf


class ErrorCode(object):
    None_ = 0
    CrcError = 1
    UnknownCommand = 2
    MissingData = 3
    NoMemory = 4
    InternalError = 5
    UnknownVariable = 6
    InvalidData = 7
    Timeout = 8
