# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DebugFlatbuf


class ResponseData(object):
    NONE = 0
    Int = 1
    UInt = 2
    Float = 3
    GetVarInfoResponse = 4
