# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DebugFB


class CmdCode(object):
    Mode = 0
    Peek = 1
    Poke = 2
    Console = 3
    Variable = 4
    Trace = 5
    EepromAccess = 6
